# How do I get :latest?  Does this imply :latest?  How do I specify the version? 
FROM quay.io/fedora/fedora-bootc:42
RUN dnf install -y [system agents] [dependencies] && dnf clean all
#COPY [unpackaged application]
#COPY [configuration files]
#RUN [config scripts]
RUN /usr/bin/bash
